package com.example.applemaps.ui

// GENERATED by pipeline/2_geometry_to_compose.py from spec/layout/phone_geometry.json.
// Do not hand-edit; re-run the script. Every number below is measured from maps.apple.com
// at a 390x844 phone viewport (logical px == dp).
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.expandIn
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.shrinkOut
import androidx.compose.animation.core.tween
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.applemaps.R
import com.example.applemaps.map.MapSurface
import com.example.applemaps.map.ConsumerMapController
import com.example.applemaps.map.ConsumerSelectedPlace
import com.example.applemaps.map.MapCoordinate
import com.example.applemaps.map.AppleHomeCategory
import com.example.applemaps.map.AppleHomeContent
import com.example.applemaps.ui.components.*

@Composable
fun GeneratedAppleLayout(
    mapController: ConsumerMapController,
    sheetController: com.example.applemaps.ui.components.AppleSheetController? = null,
    pin: MapCoordinate? = null,
    showBalloon: Boolean = true,   // false = minimize the balloon to just the ground dot
    pinTint: androidx.compose.ui.graphics.Color = androidx.compose.ui.graphics.Color(0xFFFF3B30),
    pinFace: androidx.compose.ui.graphics.ImageBitmap? = null,
    pinLabel: String = "Marked Location",
    baseSheetVisible: Boolean = true,   // false while the place card covers it (Back restores it)
    chromeVisible: Boolean = true,      // false in navigation mode (hide map-type/locate buttons + legal links)
    buildings3DEnabled: Boolean = true,
    onMapLongClick: (MapCoordinate) -> Unit = {},
    onPlaceSelected: (ConsumerSelectedPlace) -> Unit = {},
    onMapGesture: () -> Unit = {},
    placeHeader: (@Composable ColumnScope.() -> Unit)? = null,
    placeBody: (@Composable ColumnScope.() -> Unit)? = null,
    onMapType: () -> Unit = {},
    onLocate: () -> Unit = {},
    locationEnabled: Boolean = false,
    onSearch: () -> Unit = {},
    homeContent: AppleHomeContent? = null,
    homeLoading: Boolean = true,
    homeError: String? = null,
    onCategory: (AppleHomeCategory) -> Unit = {},
    onGuide: (String) -> Unit = {},
    collapsedPeek: androidx.compose.ui.unit.Dp? = null,   // place-card state uses a shorter peek (name only)
) {
    Box(Modifier.fillMaxSize()) {
        MapSurface(mapController, Modifier.fillMaxSize(), pin = pin, showBalloon = showBalloon, pinTint = pinTint, pinFace = pinFace, pinLabel = pinLabel, onMapLongClick = onMapLongClick, onPlaceSelected = onPlaceSelected, onMapGesture = onMapGesture, locationEnabled = locationEnabled, buildings3DEnabled = buildings3DEnabled)

        // topRightMapControls — white 44dp map-mode/location pill. Geometry-only corner reveal on
        // navigation enter/exit; opacity is intentionally unchanged so expansion is not mixed with a fade.
        AnimatedVisibility(
            visible = chromeVisible,
            enter = expandIn(tween(250), expandFrom = Alignment.TopEnd),
            exit = shrinkOut(tween(220), shrinkTowards = Alignment.TopEnd),
            modifier = Modifier.align(Alignment.TopEnd),
        ) {
            Column(Modifier.statusBarsPadding().padding(top = 20.dp, end = 10.dp)) {
                AppleControlButton(R.drawable.ic_map_fill_semibold, R.string.cd_map_type,
                    size = 44.dp, shape = RoundedCornerShape(topStart = 12.dp, topEnd = 12.dp, bottomEnd = 0.dp, bottomStart = 0.dp), onClick = onMapType)
                AppleControlButton(R.drawable.ic_location_semibold, R.string.cd_current_location,
                    size = 44.dp, shape = RoundedCornerShape(topStart = 0.dp, topEnd = 0.dp, bottomEnd = 12.dp, bottomStart = 12.dp), onClick = onLocate)
            }
        }

        // bottomLegalLinks — legal attribution is the one approved chrome element that fades.
        AnimatedVisibility(visible = chromeVisible, enter = fadeIn(tween(250)), exit = fadeOut(tween(200)),
            modifier = Modifier.align(Alignment.BottomCenter)) {
            LegalLinks(Modifier.padding(bottom = 122.dp))
        }

        // bottom sheet — measured 124dp peek; user-lowered 116dp rest hides clipped Find Nearby text
        if (baseSheetVisible) {
        AppleBottomSheet(
            peekHeight = collapsedPeek ?: 116.dp,
            topRadius = 14.dp,   // iOS-style corner (web measured 12px; user override)
            modifier = Modifier.align(Alignment.BottomCenter),
            controller = sheetController,
            header = {
                if (placeHeader != null) placeHeader() else {
                    SheetBrandRow(Modifier.padding(start = 20.dp, top = 16.dp))
                    AppleSearchField(
                        Modifier.padding(start = 16.dp, end = 16.dp, top = 0.dp).fillMaxWidth(),
                        onClick = onSearch,
                    )
                }
            },
            body = { if (placeBody != null) placeBody() else HomeFrontPage(homeContent, homeLoading, homeError, onCategory, onGuide) },
        )
        }
    }
}
