package com.example.applemaps.ui

// GENERATED by pipeline/6_generate_sheet_content.py from spec/layout/sheet_contents.json (measured
// from the real maps.apple.com expanded sheet). Do not hand-edit; re-run the script.
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.foundation.Image
import com.example.applemaps.R
import com.example.applemaps.ui.components.AppleAppearOnce
import com.example.applemaps.ui.theme.LocalAppleColors

private data class Category(val label: String, val icon: Int)

private val NEARBY = listOf(
    Category("Groceries", R.drawable.ic_cat_groceries),
    Category("Gas Stations", R.drawable.ic_cat_gas_stations),
    Category("Dinner", R.drawable.ic_cat_dinner),
    Category("Fast Food", R.drawable.ic_cat_fast_food),
    Category("Bars", R.drawable.ic_cat_bars),
    Category("Hotels", R.drawable.ic_cat_hotels),
    Category("Coffee", R.drawable.ic_cat_coffee),
    Category("Parking", R.drawable.ic_cat_parking),
    Category("Convenience", R.drawable.ic_cat_convenience),
)

/** The expanded-sheet content: "Find Nearby" category grid + business card + legal/copyright. */
@Composable
fun SheetContent(modifier: Modifier = Modifier) {
    val c = LocalAppleColors.current
    Column(modifier.padding(horizontal = 16.dp)) {
        AppleAppearOnce(0) {
            Text("Find Nearby", color = c.glyphDefault, fontSize = 20.sp, fontWeight = FontWeight.SemiBold,
                modifier = Modifier.padding(top = 20.dp, bottom = 12.dp))
        }
        // 2-column category grid (measured chip 173x50 r16 white, ~12dp gaps), staggered entrance
        NEARBY.chunked(2).forEachIndexed { i, pair ->
            AppleAppearOnce(i + 1) {
                Row(Modifier.fillMaxWidth().padding(bottom = 12.dp), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    pair.forEach { cat -> CategoryChip(cat, Modifier.weight(1f)) }
                    if (pair.size == 1) Spacer(Modifier.weight(1f))
                }
            }
        }
        Spacer(Modifier.height(16.dp))
        // business card
        Column {
            Text("Have a Business on Maps?", color = c.glyphDefault, fontSize = 15.sp)
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text("Manage Your Business", color = c.borderBrandAccent, fontSize = 15.sp, fontWeight = FontWeight.Medium)
                Spacer(Modifier.width(3.dp))
                Image(painterResource(R.drawable.ic_arrow_up_right), null,
                    Modifier.size(10.dp), colorFilter = ColorFilter.tint(c.borderBrandAccent))
            }
        }
        Spacer(Modifier.height(20.dp))
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(10.dp)) {
            listOf(R.string.legal_privacy, R.string.legal_terms, R.string.legal_legal, R.string.legal_imagery)
                .forEach { Text(androidx.compose.ui.res.stringResource(it), color = c.glyphMuted, fontSize = 11.sp) }
        }
        Text("Copyright © 2026 Apple Inc. All rights reserved.", color = c.glyphMuted, fontSize = 11.sp,
            modifier = Modifier.padding(top = 4.dp, bottom = 24.dp))
    }
}

@Composable
private fun CategoryChip(cat: Category, modifier: Modifier = Modifier) {
    val c = LocalAppleColors.current
    Row(
        modifier.height(50.dp).clip(RoundedCornerShape(16.dp)).background(androidx.compose.ui.graphics.Color.White)
            .clickable { }.padding(horizontal = 12.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Image(painterResource(cat.icon), cat.label, Modifier.size(30.dp))  // real colored Apple icon, no tint
        Spacer(Modifier.width(8.dp))
        Text(cat.label, color = c.glyphDefault, fontSize = 17.sp, fontWeight = FontWeight.Normal)
    }
}
