package com.example.applemaps.ui.anim

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.Easing

/**
 * Apple Maps motion constants — GENERATED by spec/anim_to_kotlin.py from the easing/duration
 * catalog extracted verbatim from the real maps.apple.com assets (spec/anim_catalog/,
 * spec/ANIMATION_MODEL.md). Do not hand-edit; re-run the script. NO physics bounce — the
 * overshoot look comes from Overshoot's y>1 control point.
 */
object AppleEasing {
    /** popover pop / context menu (y>1 overshoot, NOT physics) — cubic-bezier(0.25,0.1,0.25,1.3) */
    val Overshoot: Easing = CubicBezierEasing(0.25f, 0.1f, 0.25f, 1.3f)
    /** general ease — cubic-bezier(0.25,0.1,0.25,1.0) */
    val Standard: Easing = CubicBezierEasing(0.25f, 0.1f, 0.25f, 1.0f)
    /** bottom-sheet settle / momentum — cubic-bezier(0.19,1.0,0.22,1.0) */
    val ExpoOut: Easing = CubicBezierEasing(0.19f, 1.0f, 0.22f, 1.0f)
    /** mobile page-out — cubic-bezier(1.0,0.1,0.0,0.3) */
    val Exit: Easing = CubicBezierEasing(1.0f, 0.1f, 0.0f, 0.3f)
    /** misc transitions — cubic-bezier(0.03,0.0,0.31,1.0) */
    val CurveA: Easing = CubicBezierEasing(0.03f, 0.0f, 0.31f, 1.0f)
    /** misc transitions — cubic-bezier(0.12,0.55,0.19,1.0) */
    val CurveB: Easing = CubicBezierEasing(0.12f, 0.55f, 0.19f, 1.0f)
    /** ease-in — cubic-bezier(0.64,0.0,0.85,1.0) */
    val EaseIn: Easing = CubicBezierEasing(0.64f, 0.0f, 0.85f, 1.0f)
    /** misc — cubic-bezier(0.333333,0.0,0.666667,0.333333) */
    val CurveD: Easing = CubicBezierEasing(0.333333f, 0.0f, 0.666667f, 0.333333f)
    /** bottom-sheet settle — FITTED from the measured drag trajectory (pipeline/8) — cubic-bezier(0.4,0.6,0.0,1.0) */
    val SheetSettle: Easing = CubicBezierEasing(0.4f, 0.6f, 0.0f, 1.0f)
    /** CSS `ease-out` — cubic-bezier(0,0,0.58,1); the real `.mw-card` transform/opacity transition (.15s). */
    val EaseOutStd: Easing = CubicBezierEasing(0.0f, 0.0f, 0.58f, 1.0f)
}

/** Verified animation durations (ms) from CSS + JS + the MapKit engine. */
object AppleDuration {
    const val ControlWipe = 250   // floating-control corner wipe / context menu / sidebar
    const val Popover = 200   // popover pop
    const val Fade = 150   // opacity/visibility fades
    const val SearchField = 250   // search field expand (.25s ease-out)
    const val SearchResult = 140   // search result item (.14s ease-out)
    const val SheetSettle = 300   // bottom-sheet settle to detent
    const val PoiPop = 200   // MapKit annotation/cluster appear
    const val Callout = 500   // business callout / selection accessory fade
    const val RouteLine = 350   // directions overlay (blue route) fade-in
    const val Camera = 250   // map camera pan/zoom/flyTo
}
